"use client";

import { useEffect, useState } from "react";
import { formatCurrency } from "@/lib/utils";

type Product = { id: string; name: string; category: { name: string } };
type Promotion = { id: string; title: string; description: string | null; price: string | number; startsAt: string; endsAt: string; active: boolean; items: Array<{ quantity: number; product: { name: string } }> };
function localDate(date: Date) { return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export default function PromoClubPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [promotions, setPromotions] = useState<Promotion[]>([]);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [price, setPrice] = useState("");
  const [startsAt, setStartsAt] = useState(localDate(new Date())); const [endsAt, setEndsAt] = useState(localDate(new Date(Date.now() + 7 * 86400000)));
  const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const [p, c] = await Promise.all([fetch("/api/prodotti"), fetch("/api/promo-club")]); if (p.ok) setProducts(await p.json()); if (c.ok) setPromotions(await c.json()); }
  useEffect(() => { load(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/promo-club", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, description: description || null, price: Number(price), startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString(), items: selected.map((productId) => ({ productId, quantity: 1 })) }) }); if (response.ok) { setTitle(""); setDescription(""); setPrice(""); setSelected([]); setMessage("Promo Club programmata."); await load(); } else setMessage("Impossibile salvare la promo."); setSaving(false); }
  async function remove(id: string) { if (!confirm("Eliminare questa promo?")) return; await fetch(`/api/promo-club?id=${id}`, { method: "DELETE" }); load(); }
  return <div className="max-w-5xl"><div className="mb-10"><span className="ds-micro-label text-terracotta/60">Club</span><h1 className="mt-2 font-display text-5xl tracking-tight">Promo <span className="text-terracotta">Club.</span></h1><p className="mt-3 font-body italic text-charcoal/45">Programma due offerte settimanali, anche in formato combo.</p></div>
    <form onSubmit={save} className="mb-10 space-y-5 rounded-[2rem] border border-charcoal/5 bg-white p-7 shadow-sm"><h2 className="font-brand text-lg font-semibold">Nuova promo</h2><div className="grid gap-4 md:grid-cols-2"><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Es. Combo pizza + bibita" className="rounded-xl border border-charcoal/10 px-4 py-3" /><input required type="number" min="0" step="0.01" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="Prezzo combo €" className="rounded-xl border border-charcoal/10 px-4 py-3" /></div><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Descrizione breve" rows={2} className="w-full rounded-xl border border-charcoal/10 px-4 py-3" /><div className="grid gap-4 md:grid-cols-2"><label className="text-xs font-semibold text-charcoal/55">Inizio<input required type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} className="mt-1 w-full rounded-xl border border-charcoal/10 px-4 py-3 text-sm" /></label><label className="text-xs font-semibold text-charcoal/55">Fine<input required type="datetime-local" value={endsAt} onChange={(e) => setEndsAt(e.target.value)} className="mt-1 w-full rounded-xl border border-charcoal/10 px-4 py-3 text-sm" /></label></div><div><p className="mb-2 text-xs font-semibold text-charcoal/55">Prodotti inclusi nella combo</p><div className="grid max-h-52 gap-2 overflow-y-auto rounded-xl bg-warm-light p-3 md:grid-cols-2">{products.map((product) => <label key={product.id} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm"><input type="checkbox" checked={selected.includes(product.id)} onChange={() => setSelected((current) => current.includes(product.id) ? current.filter((id) => id !== product.id) : [...current, product.id])} />{product.name}<span className="ml-auto text-[10px] text-charcoal/35">{product.category.name}</span></label>)}</div></div><div className="flex items-center justify-between gap-4"><p className="text-xs text-charcoal/45">Visibile solo agli utenti Club nel periodo indicato.</p><button disabled={saving || selected.length === 0} className="rounded-full bg-charcoal px-6 py-3 text-xs font-bold uppercase tracking-widest text-white disabled:opacity-40">{saving ? "Salvataggio…" : "Programma promo"}</button></div>{message && <p className="text-sm font-semibold text-terracotta">{message}</p>}</form>
    <div className="space-y-3">{promotions.map((promotion) => <div key={promotion.id} className="flex flex-col gap-3 rounded-2xl border border-charcoal/5 bg-white p-5 md:flex-row md:items-center md:justify-between"><div><h3 className="font-display text-2xl">{promotion.title}</h3><p className="text-sm text-charcoal/55">{promotion.items.map((item) => `${item.quantity > 1 ? `${item.quantity}× ` : ""}${item.product.name}`).join(" + ")} · {formatCurrency(Number(promotion.price))}</p><p className="text-xs text-charcoal/35">{new Date(promotion.startsAt).toLocaleString("it-IT")} → {new Date(promotion.endsAt).toLocaleString("it-IT")}</p></div><button onClick={() => remove(promotion.id)} className="self-start text-xs font-bold uppercase tracking-widest text-red-400">Elimina</button></div>)}</div></div>;
}
